---
- name: Wait for Devspaces namespace creation
  k8s_info:
    api_version: v1
    kind: Namespace
    name: "{{ rhpds_build_secured_dev_workflows_developer_hub_devspaces_namespace }}"
  register: r_devspaces
  retries: 180
  delay: 10
  until:
  - r_devspaces.resources | length > 0

- name: Create Devspaces GitLab application
  ansible.builtin.uri:
    url: "https://{{ _rhpds_build_secured_dev_workflows_developer_hub_gitlab_host }}/api/v4/applications"
    method: POST
    body_format: form-urlencoded
    body:
      name: devspaces
      redirect_uri: "https://{{ _rhpds_build_secured_dev_workflows_developer_hub_devspaces_host }}/api/oauth/callback"
      scopes: api read_user read_repository write_repository sudo openid profile email
      confidential: false
    headers:
      PRIVATE-TOKEN: "{{ _rhpds_build_secured_dev_workflows_developer_hub_gitlab_root_token }}"
    validate_certs: false
    status_code: [201]
  register: r_devspaces_app
  retries: 60
  delay: 10
  until: r_devspaces_app.status == 201

- name: Get Keycloak client credentials
  ansible.builtin.set_fact:
    _rhpds_build_secured_dev_workflows_developer_hub_devspaces_client_id: "{{ r_devspaces_app.json.application_id }}"
    _rhpds_build_secured_dev_workflows_developer_hub_devspaces_client_secret: "{{ r_devspaces_app.json.secret }}"

- name: Create Devspaces oauth config for Gitlab
  kubernetes.core.k8s:
    state: present
    namespace: "{{ rhpds_build_secured_dev_workflows_developer_hub_devspaces_namespace }}"
    template: "devspaces-gitlab-oauth.yml.j2"