---
- name: Get Realm Management role
  uri:
    url: https://{{ _rhpds_build_secured_dev_workflows_developer_hub_keycloak_host }}/admin/realms/trusted-artifact-signer/clients/{{
      _rhpds_build_secured_dev_workflows_developer_hub_dh_rm_client_id }}/roles/{{ _role }}
    method: GET
    validate_certs: false
    headers:
      Authorization: Bearer {{ _rhpds_build_secured_dev_workflows_developer_hub_keycloak_access_token }}
  register: r_rm_client_role

- name: Import role to service account
  uri:
    url: https://{{ _rhpds_build_secured_dev_workflows_developer_hub_keycloak_host }}/admin/realms/trusted-artifact-signer/users/{{
      _rhpds_build_secured_dev_workflows_developer_hub_dh_sa_id }}/role-mappings/clients/{{ _rhpds_build_secured_dev_workflows_developer_hub_dh_rm_client_id }}
    method: POST
    validate_certs: false
    body_format: json
    headers:
      Authorization: Bearer {{ _rhpds_build_secured_dev_workflows_developer_hub_keycloak_access_token }}
    body: ["{{ r_rm_client_role.json }}"]
    status_code: 204